In [1]:
!pip3 install pandas

  Using cached pandas-3.0.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Using cached pandas-3.0.1-cp313-cp313-macosx_11_0_arm64.whl (9.9 MB)


In [6]:
import pandas as pd
a=[[1,2,3],[4,5,6],[7,8,9]]
df1=pd.DataFrame(a,index=['row1','row2','row3'],columns=['col1','col2','col3'])
df1

,col1,col2,col3
row1,1,2,3
row2,4,5,6
row3,7,8,9


In [5]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
np1=np.array(a)
print(np1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
df2=pd.DataFrame(np1,index=['r1','r2','r3'],columns=['c1','c2','c3'])
df2

,c1,c2,c3
r1,1,2,3
r2,4,5,6
r3,7,8,9


In [9]:
d1={'Name':['Alice','Bob','Charlie'],
    'Age':[25,30,35],
    'City':['New York','Los Angeles','Chicago']}
df3=pd.DataFrame(d1)
df3

,Name,Age,City
0,Alice,25,New York
1,Bob,30,Los Angeles
2,Charlie,35,Chicago


In [10]:
l1=[{'Name':'Alice','Age':25,'City':'New York'},
    {'Name':'Bob','Age':30,'City':'Los Angeles'},
    {'Name':'Charlie','Age':35,'City':'Chicago'}]
df4=pd.DataFrame(l1)
df4

,Name,Age,City
0,Alice,25,New York
1,Bob,30,Los Angeles
2,Charlie,35,Chicago
